# Generated by Django 3.1 on 2022-06-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ether',
            name='ether_address',
            field=models.CharField(default='address', max_length=100),
        ),
        migrations.AlterField(
            model_name='ether',
            name='ether_password',
            field=models.CharField(default='password', max_length=20),
        ),
    ]
