# Generated by Django 3.1 on 2022-06-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_best',
            field=models.BooleanField(default=False),
        ),
    ]
