# Generated by Django 3.1 on 2022-05-29 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220518_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ether',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ether_address', models.CharField(max_length=100)),
                ('ether_wallet', models.IntegerField()),
                ('ether_anonymous', models.BooleanField()),
                ('ether_password', models.CharField(max_length=20)),
                ('ether_account_name', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=50)),
                ('question_content', models.TextField()),
                ('question_source_code', models.TextField()),
                ('question_post_time', models.DateTimeField()),
                ('question_status', models.BooleanField(default=False)),
                ('question_value', models.IntegerField(default=0)),
                ('question_number_of_responses', models.IntegerField(default=0)),
                ('ether_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ether')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.TextField()),
                ('answer_source_code', models.TextField()),
                ('answer_post_time', models.DateTimeField()),
                ('answer_value', models.IntegerField()),
                ('answer_best', models.BooleanField()),
                ('eth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ether')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
    ]
