# Generated by Django 3.1 on 2022-06-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220623_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_user_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
