# Generated by Django 3.1 on 2022-06-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
