# Generated by Django 3.1 on 2022-05-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answer_ether_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ether',
            name='ether_wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_source_code',
            field=models.TextField(null=True),
        ),
    ]
