# Generated by Django 3.1 on 2022-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220626_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ether',
            name='ether_account_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ether',
            name='ether_anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
