# Generated by Django 3.1 on 2022-06-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220621_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='ether',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.CharField(max_length=10, null=True, verbose_name='グループ'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
