# Generated by Django 3.1 on 2022-06-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220626_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False, help_text='学生ならfalse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.CharField(default='', max_length=10, verbose_name='グループ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='名前'),
        ),
    ]
