# Generated by Django 3.1 on 2022-06-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220626_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_content',
            field=models.TextField(default='内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.TextField(default='内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='タイトル', max_length=50),
        ),
    ]
